- bin/zappifest
- lib/network_helpers.rb
Wait with deployment for the relevant `Zapp` deployment.
> improvement: send type as category param request

- lib/zappifest.rb
Adding inquirer gem for better ui
> adding inquirer gem and use it for better ui

- lib/manifest_helpers.rb
- lib/zappifest.rb
This PR is adding `User-Agent` header and ensuring whitelisted keys before publishing
> adding whitelist keys and user-agent

- lib/data_source_provider_questions_helper.rb
- lib/default_questions_helper.rb
Fixed typo and removed underscore on Type Label
> Fixed typo and removed underscore on Type Label

- lib/plugin.rb
- lib/plugin_base.rb
- lib/plugin_version.rb
- lib/zappifest.rb
This PR adds a `--new` flag in the cli options to create a new plugin
> add cli flag to create new plugin

- lib/manifest_helpers.rb
Adds `article` type to zappifest
> add article type to zappifest

- lib/navigation_plugins_questions_helper.rb
- lib/zappifest.rb
Adding questions to support `supported_nav_items`
> chore(nav items): add selector for supported nav items on Navigation types plugins

- lib/default_questions_helper.rb
- lib/question.rb
Validating versions  questions using `Versionomy`
> feat(versions): validate version input

- lib/navigation_plugins_questions_helper.rb
This PR changes from collapsed to nested_menu in navigation_helper
> fix(navigation_helper): changes from collapsed to nested_menu

- lib/navigation_plugins_questions_helper.rb
This PR adds new nav_items options to navigation_plugins_questions_helper.rb
> feature(navigations_helper): adds new nav_items options

- lib/plugin.rb
Fixing ridiculous bug that was always sending true
> fix(plugin publish): remove bug when support ui builder is always true

- lib/manifest_helpers.rb
validate ui builder support key
> feat(manifest keys): validate ui_builder_support key

- lib/default_questions_helper.rb
Not allowing to leave field blank when user provides input
> feat(account ids): validate whitelisted accounts on init

- lib/default_questions_helper.rb
- lib/question.rb
Removing default value and force putting a version
> Remove default value for min sdk

- lib/default_questions_helper.rb
- lib/network_helpers.rb
Using Zapp SDK api to get the latest stable version
> feat(min zapp sdk):setting minimum sdk as latest stable on zapp

- lib/api_questions_helper.rb
- lib/data_source_provider_questions_helper.rb
- lib/default_questions_helper.rb
- lib/zappifest.rb
Edit some of the questions during the `zappifest init` process so it will be more clear to the developer.
> chore(zappifest init): questions improvements

- lib/manifest_helpers.rb
Adding roku as supported platform
> feat(roku): add roku as supported platform

- lib/custom_fields_questions_helper.rb
- lib/manifest_helpers.rb
adding special `assets_bundle` key to allow uploading assets zip that will extract assets to resources
> feat(custom fields): adding assets bundle uploader option

- lib/plugin.rb
> feat(plugin): add whitelisted plugin attributes that could be updated

- lib/manifest_helpers.rb
This PR adds a new plugin_type: "cell_builder"
> feat(cell_builder): adds new plugin type

- lib/plugin_version.rb
this PR is fixes plugin_version targets selection
> fix(plugin_version): fixes targets selection
